### ISSUE TITLE
Add LGPL-2.1-or-later license too

### ISSUE THREAD

**Issue by bourtemb** [conda-forge/omniorb-feedstock#10]
- [x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

OmniORB software is licensed under multiple licenses, GPL-2.0-or-later for the programs, LGPL-2.1-or-later for the libraries.
I think COPYING.LIB should also be specified in the list of [license_file metadata](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file) in the recipe.
I don't know how it works for the license metadata in the conda recipe. Can we specify a list of licenses here?
The conda-build documentation does not seem clear on that point.
If yes, I think it would be good to add LGPL-2.1-or-later to the list of licenses.

I think it would be also good to modify GPL-2.0-only to GPL-2.0-or-later too because the files in omniORB source code are specifying the "or later" option as you can see in the header of the following file:
- https://sourceforge.net/p/omniorb/svn/HEAD/tree/tags/4_2_4/omniORB/src/tool/omniidl/cxx/idltype.cc
or the following file to illustrate a file where LGPL2.1 or later license applies:
- https://sourceforge.net/p/omniorb/svn/HEAD/tree/tags/4_2_4/omniORBpy/include/omniORBpy.h

**Comment by carlodri** [comment]
Thanks for the report. After a little digging, yes, this is all possible since [SPDX identifiers](https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/) allow expressions. I will add this license stuff to #12 before merging.
